# Generated by Django 5.1.1 on 2024-09-09 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zomato', '0002_hotel_image_alter_hotel_location_alter_hotel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(blank=True, max_length=50)),
                ('food_image', models.ImageField(max_length=50, upload_to='image')),
                ('price', models.IntegerField()),
                ('comments', models.TextField(blank=True, max_length=500)),
                ('hotel_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zomato.hotel')),
            ],
        ),
    ]
